
AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/data/words'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 110
